### ISSUE TITLE
Portafolio - Mint tokens

### ISSUE THREAD

**Issue by cerotrade** [Cero-Trade/mvp1.0#21]
**User Story**
As a system operator, I want to be able to mint new tokens if new items are recognized in our Cero Trade encumberance account, given that item's asset is already linked to an existing token, in order to dinamically add IRECs to our platform.

Acceptance Criteria

- [ ] When agent recieves assetInfo, must check if asset is already associated to a token.
- [ ] If asset is associated to a token, must mint specificed amount, only if it does not exceed maximum minting amount (volumeProduced).
- [ ] Minting can only be done by authorized caller (principal with admin role)
- [ ] New token information (amount of it owned by user) must be updated in Users canister, in TokenList --> totalAmount
- [ ] Frontend must reflect changes

**Tasks**

# Mint Token Process Tasks

## Initial Checks and Verification

- [ ] **Develop `checkTokenAsset` Function:**
  - Implement a method to verify if the asset associated with the `assetID` is already linked to a token in the TokenIndex canister.

## Token Canister Interaction

- [ ] **Implement `getTokenCanister` Method:**
  - Code the logic to interact with the TokenIndex canister to verify assetID existence within `TokenLocationMap`.

## Minting and Error Handling

- [ ] **Create New Token Logic:**
  - Outline the process for creating a new token when there is no existing token linked to an asset.

- [ ] **Implement `mint` Function:**
  - Code the `mint(principal, amount)` function to handle the minting of new tokens.

## Authorization Verification

- [ ] **Code Authorization Logic:**
  - Ensure the minting process is initiated by an authorized caller with the admin role.

## User Canister Update

- [ ] **Develop `addTokenToUser` Function:**
  - Implement the method to update the Users canister with new token information, reflecting in `TokenList`.

## User Interface Updates

- [ ] **Frontend Integration for Displaying Updated Tokens:**
  - Develop frontend components and logic for displaying updated token information in the portfolio.

## User Tracking and Validation

- [ ] **Implement `trackUser` Method:**
  - Code the method to locate and update the user canister in `userIndex` post minting.

**Comment by cerotrade** [comment]
**USEFUL LINKS:**

https://www.notion.so/cerotrade/ICRC-1-y-ICRC-2-9f4f81a0cd454fca88594a7ed95f8ea6

@detextre4 ahí está todo lo referente a ICRC-1 e ICRC-2
