### ISSUE TITLE
[BACKEND DEVELOPMENT - WEB2] Handle and retrieve Transactions from /accounts Endpoint

### ISSUE THREAD

**Issue by cerotrade** [Cero-Trade/mvp1.0#78]
**Description:** 

This task involves creating an ednpoint that retrieves transactions from the /accounts endpoint in the Evident API, also getting necessary details.

**Tasks:**

- [ ]  Call the /accounts endpoint to retrieve transactions.
- [ ]  Extract date from transactions.
- [ ]  Extract items contained in the transactions.
- [ ]  Extract account ID from the transactions.
- [ ] Extract volume of transaction.
- [ ] Extract asset ID from items.
- [ ] Extract energy source and country from asset.
- [ ]  Handle API responses and errors.
